repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-added-large-files
    args: ['--maxkb=500']
  - id: check-executables-have-shebangs
  - id: pretty-format-json
    args: ['--autofix', '--no-sort-keys', '--indent=2']
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: detect-private-key
  - id: debug-statements
- repo: git://github.com/smian/pre-commit-makefile
  rev: 261f8fb4b31dfdc05d1a1d7fbde1f1462ecde66d
  hooks:
  - id: makefile-doc
- repo: git@github.com:Yelp/detect-secrets
  rev: v0.13.0
  hooks:
  - id: detect-secrets
    args: ['--baseline', '.secrets.baseline']
- repo: meta
  hooks:
  - id: check-useless-excludes
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.24.2
  hooks:
  - id: yamllint
    files: \.(yaml|yml)$
    types: [file, yaml]
    entry: 'yamllint --strict -d "{extends: relaxed, rules: {line-length: {max: 200}}}"'
