---
name: build-ios-app-with-fastlane
on:
  workflow_dispatch:

env:
  WORKING_DIRECTORY: ios
  ARTIFACT_NAME: artifact
  PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
  KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
  APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
  APPLE_ID: ${{ secrets.APPLE_ID }}

jobs:
  build:
    runs-on: macos-latest

    # strategy:
    #   matrix:
    #     node-version: [15.14.0]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '1'

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 15.14.0

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: cache yarn
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: cache cocoapods
        uses: actions/cache@v2
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: 'install dependencies && pod install'
        if: success()
        run: |
          make setup-dependencies

      - name: 'bundle install && pod install'
        if: success()
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          bundle install
          # pod install

      - name: actions
        if: success()
        run: make

      - name: fastlane help
        if: success()
        run: make build-ci
