---
name: build-ios-app-with-fastlane
on:
  workflow_dispatch:

env:
  WORKING_DIRECTORY: ios

jobs:
  build:
    runs-on: macos-latest

    # strategy:
    #   matrix:
    #     node-version: [15.14.0]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '1'

      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 15.14.0

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn install

      - name: Cache cocoapods
        uses: actions/cache@v2
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: install pods
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: pod install

      - name: actions
        run: make

      - name: fastlane help
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: fastlane  --help
